plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'fu.de190381'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Web MVC + Tomcat nhúng
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Thymeleaf
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

	// Bean Validation (Hibernate Validator)
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Spring Data JPA (Hibernate 6 + HikariCP)
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// JDBC driver SQL Server
	runtimeOnly 'com.microsoft.sqlserver:mssql-jdbc'

	// DevTools: tự restart khi sửa code
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
